version: '3.8'

services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp   # http proxy
      - 8388:8388/tcp   # shadowsocks
      - 8388:8388/udp   # shadowsocks
      - 8080:8080       # qbittorrent web ui
      - 6881:6881       # qbittorrent
      - 6881:6881/udp   # qbittorrent
      - 9696:9696       # prowlarr port
      - 8989:8989       # sonnar port
      - 7878:7878       # radarr port
      - 6767:6767       # bazarr port
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/glueton:/gluetun
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${OPENVPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${OPENVPN_SERVER_COUNTRIES}
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/qbittorrent:/config
      - ${ROOT_DIRECTORY}/data/torrents:/data/torrents
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 8191:8191
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 9696:9696
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/prowlarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name:  sonarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
      # - 8989:8989
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/sonarr:/config
      - ${ROOT_DIRECTORY}/data:/data
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - qbittorrent
      - prowlarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 7878:7878
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/radarr:/config
      - ${ROOT_DIRECTORY}/data:/data
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 6767:6767
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/bazarr:/config
      - ${ROOT_DIRECTORY}/data/media:/data/media
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/overseerr:/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/tautulli:/config
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=latest
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_DIRECTORY}/data/dockerdata/plex:/config
      - ${ROOT_DIRECTORY}/data/media:/data/media
    restart: unless-stopped
