version: '3.8'

services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # http proxy
      - 8388:8388/tcp # shadowsocks
      - 8388:8388/udp # shadowsocks
      - 8080:8080 # qbittorrent web ui
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 9696:9696 # prowlarr port
      - 8989:8989 # sonnar port
      - 7878:7878 # radarr port
      - 6767:6767 # bazarr port
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/glueton:/gluetun
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${OPENVPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${OPENVPN_SERVER_COUNTRIES}
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/qbittorrent:/config
      - ${DATA_ROOT_DIRECTORY:-.}/data/torrents:/data/torrents
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 8191:8191
    environment:
      - TZ=${TZ:-Etc/UTC}
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 9696:9696
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/prowlarr:/config
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 8989:8989
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/sonarr:/config
      - ${DATA_ROOT_DIRECTORY:-.}/data:/data
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - qbittorrent
      - prowlarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 7878:7878
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/radarr:/config
      - ${DATA_ROOT_DIRECTORY:-.}/data:/data
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:vpn
    # Specified in vpn service due to network mode.
    # ports:
    #   - 6767:6767
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/bazarr:/config
      - ${DATA_ROOT_DIRECTORY:-.}/data/media:/data/media
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    profiles:
      - bazarr

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/overseerr:/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    profiles:
      - overseerr

  requestrr:
    image: thomst08/requestrr:latest
    container_name: requestrr
    ports:
      - 4545:4545
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/requestrr:/root/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    profiles:
      - requestrr

  maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    user: ${PUID}:${PGID}
    ports:
      - 6246:6246
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/maintainerr:/opt/data
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    profiles:
      - maintainerr

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8181:8181
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/tautulli:/config
    restart: unless-stopped
    profiles:
      - tautulli

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=latest
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/plex:/config
      - ${DATA_ROOT_DIRECTORY:-.}/data/media:/data/media
    restart: unless-stopped

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    ports:
      - 80:80
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA_ROOT_DIRECTORY:-.}/dockerdata/organizr:/config
    restart: unless-stopped
    profiles:
      - organizr
